name: PR compliance check
# This job verifies that the PR's title contains an SPTL issue reference.
# If there is no reference in the title, then it tries to deduce the ticket reference,
# either from the branch name, or from the PR's comment.
# In the rare cases where the PR does not have a relevant ticket, we can use 'SPTL-NA' as the ticket reference

on:
  pull_request_target:
    branches: [ master ]
    types:
      - opened
      - reopened
      - edited
      - synchronized
  workflow_call:

permissions:
  pull-requests: write

jobs:
  verify_ticket_reference_in_title:
    runs-on: ubuntu-latest
    steps:
      - uses: glowwVideo/ticket-check-action@v0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketPrefix: 'SPTL-'
          titleRegex: 'SPTL-(?<ticketNumber>\d+|NA)'
          branchRegex: 'SPTL-(?<ticketNumber>\d+)'
          bodyRegex: 'SPTL-(?<ticketNumber>\d+)'

